import type { NextPage } from 'next';
import Head from 'next/head';
import { Repos, Search, User, UserInfo } from '../components';
import Layout from '../layout/Layout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>OctoProfile | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isHome={true}>
        <Search />
        <UserInfo />
        <User />
        <Repos />
      </Layout>
    </div>
  );
};

export default Home;
