import type { NextPage } from 'next';
import Head from 'next/head';
import { User, UserInfo } from '../components';
import Layout from '../layout/Layout';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isHome={true}>
        <h1>Homepage</h1>
        <UserInfo />
        <User />
      </Layout>
    </div>
  );
};

export default Home;
